### ISSUE TITLE
gaussian filter has no "Run" button

### ISSUE THREAD

**Issue by dmichalak** [brisvag/blik#170]
After loading a tomogram (`.mrc` format), clicking on Plugins ->  blik -> gaussian filter brings up the widget showing `image`, `sigma`, and `kernel size` parameters but there is no button to apply the filter. Is there another one to run it?

**Comment by brisvag** [comment]
The filter runs automatically as soon as you change the parameters. Select the layer with the dropdown menu, then move the slider and you'll see it update live!

**Comment by dmichalak** [comment]
You are absolutely right! Thank you very much.
