### ISSUE TITLE
Examples, preferably with data

### ISSUE THREAD

**Issue by alisterburt** [brisvag/blik#18]
ideally we want examples for the following
- Particles on tomogram
- Refinement results viewing
- Template matching results viewing
- Transformation block applied to chemoreceptor data (hexagon -> c2 axes)

**Comment by brisvag** [comment]
Importantly, we shouldn't clutter and weigh down the repo with heavy data. We should either host them on a separate repo that doesn't need frequent updates, or even better we should set up some script to download the necessary data from somewhere.
